# Pratical TensorFlow with python (REF,(BOOK : Tensorflow for deep learning, Author: Bharath, Reza))

In [1]:
import tensorflow as tf

D:\Users\hariharan-v\AppData\Local\Continuum\anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


#### interactive session in tensorflow 
* allowing users to play with tensors much more easily
* this will allow TF behave imperatively

In [2]:
tf.InteractiveSession()

#### initializing constant tensors
* tf.zeros() - takes a tensor of shape (reprasented as a python tuple)
* returns a tensor of shape filles with zeros

In [3]:
tf.zeros(2)

<tf.Tensor 'zeros:0' shape=(2,) dtype=float32>

In [4]:
tf.ones(2)

<tf.Tensor 'ones:0' shape=(2,) dtype=float32>

* TF retuns the ref to the desired tensor rather than the value of the tensor itself 
* since we have used the tf interactive session we use the following method tf.Tensor.eval() to return the value the value of the tensor

In [5]:
a= tf.zeros(2)

In [6]:
a.eval() # the return value is itself a python object (it is numpy.ndarray object)

array([0., 0.], dtype=float32)

* TF is designed to be compatible with numpy conventions to a large degree

In [7]:
a = tf.zeros((2,3))

In [8]:
a.eval()

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [9]:
b = tf.ones((2,2,2))

In [10]:
b.eval()

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)

* to fill the tensors besides 0/1 we use the follwing meothod to do so

In [11]:
b = tf.fill((2,2), value=5.)

In [12]:
b.eval()

array([[5., 5.],
       [5., 5.]], dtype=float32)

* tf.constant is another function, similar to tf.fill which allows for constructing tensors that should not change during excecution 

In [13]:
a= tf.constant(3)

In [14]:
a.eval()

3

* sampling the values of the tensor from a normal distribution (specified mean and variance) is much more comman way to initialize tensors
* weights should be initialized using sampling from normal distribution since weight with same values evolve together so the model won't be capable of learn better.

In [15]:
a = tf.random_normal((2,2), mean=0, stddev=1)

In [16]:
a.eval()

array([[ 2.8051686, -1.2457492],
       [-1.359344 ,  1.1708003]], dtype=float32)

* when we sample values for a very large tensors , it becomes almost certain that sampled values will be far from the mean. 
* such large samples can lead to numerical instablity, so it is common to sample using tf.truncated_normal() instead of tf.random_normal()
* tf.random_uniform() behaves like a tf.random_normal() except for the fact that random values are sampled form the uniform distribution 

In [17]:
a=tf.random_uniform((2,2),minval=-2,maxval=2)
a.eval()

array([[ 0.38132668,  0.05907869],
       [ 1.6857448 , -0.2766614 ]], dtype=float32)