# Pratical TensorFlow with python (REF,(BOOK : Tensorflow for deep learning, Author: Bharath, Reza))

In [1]:
import tensorflow as tf

#### interactive session in tensorflow 
* allowing users to play with tensors much more easily
* this will allow TF behave imperatively

In [2]:
tf.InteractiveSession()

#### initializing constant tensors
* tf.zeros() - takes a tensor of shape (reprasented as a python tuple)
* returns a tensor of shape filles with zeros

In [3]:
tf.zeros(2)

<tf.Tensor 'zeros:0' shape=(2,) dtype=float32>

In [4]:
tf.ones(2)

<tf.Tensor 'ones:0' shape=(2,) dtype=float32>

* TF retuns the ref to the desired tensor rather than the value of the tensor itself 
* since we have used the tf interactive session we use the following method tf.Tensor.eval() to return the value the value of the tensor

In [5]:
a= tf.zeros(2)

In [6]:
a.eval() # the return value is itself a python object (it is numpy.ndarray object)

array([ 0.,  0.], dtype=float32)

* TF is designed to be compatible with numpy conventions to a large degree

In [7]:
a = tf.zeros((2,3))

In [8]:
a.eval()

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]], dtype=float32)

In [9]:
b = tf.ones((2,2,2))

In [10]:
b.eval()

array([[[ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.]]], dtype=float32)

* to fill the tensors besides 0/1 we use the follwing meothod to do so

In [11]:
b = tf.fill((2,2), value=5.)

In [12]:
b.eval()

array([[ 5.,  5.],
       [ 5.,  5.]], dtype=float32)

* tf.constant is another function, similar to tf.fill which allows for constructing tensors that should not change during excecution 

In [13]:
a= tf.constant(3)

In [14]:
a.eval()

3

* sampling the values of the tensor from a normal distribution (specified mean and variance) is much more comman way to initialize tensors
* weights should be initialized using sampling from normal distribution since weight with same values evolve together so the model won't be capable of learn better.

In [15]:
a = tf.random_normal((2,2), mean=0, stddev=1)

In [16]:
a.eval()

array([[-0.81985384, -0.83342886],
       [ 0.05886778, -0.91798997]], dtype=float32)

* when we sample values for a very large tensors , it becomes almost certain that sampled values will be far from the mean. 
* such large samples can lead to numerical instablity, so it is common to sample using tf.truncated_normal() instead of tf.random_normal()
* tf.random_uniform() behaves like a tf.random_normal() except for the fact that random values are sampled form the uniform distribution 

In [17]:
a=tf.random_uniform((2,2),minval=-2,maxval=2)
a.eval()

array([[-1.87264252, -1.6424613 ],
       [ 0.93856335, -0.59700489]], dtype=float32)

#### tensor addition and scaling

In [18]:
c= tf.ones((2,2))

In [19]:
d= tf.ones((2,2))

In [20]:
e=c+d

In [21]:
e.eval()

array([[ 2.,  2.],
       [ 2.,  2.]], dtype=float32)

In [22]:
f=e*2 # note this elementwise multiplication and not matrix multiplication

In [23]:
f.eval()

array([[ 4.,  4.],
       [ 4.,  4.]], dtype=float32)

* elementwise tensor multiplication


In [24]:
c=tf.fill((2,2),2.)
d=tf.fill((2,2),7.)


In [25]:
e=c*d

In [26]:
e.eval()

array([[ 14.,  14.],
       [ 14.,  14.]], dtype=float32)

In [27]:
a=tf.eye(4)

In [28]:
a.eval()

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]], dtype=float32)

* diagonal matrix 
* unlike identity matrix the diagonal matrix takes arbitary non zero values along the diagonal 

In [29]:
r=tf.range(1,5,1)

In [30]:
r.eval()

array([1, 2, 3, 4])

In [31]:
d=tf.diag(r)

In [32]:
d.eval()

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### matrix transpose

In [33]:
a=tf.ones((2,3))

In [34]:
a.eval()

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]], dtype=float32)

In [35]:
at=tf.matrix_transpose(a)

In [36]:
at.eval()

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]], dtype=float32)

#### matrix multiplication

In [37]:
a=tf.ones((2,3))

In [38]:
a.eval()

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]], dtype=float32)

In [39]:
b=tf.ones((3,4))

In [40]:
b.eval()

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]], dtype=float32)

In [41]:
c=tf.matmul(a,b)

In [42]:
c

<tf.Tensor 'MatMul:0' shape=(2, 4) dtype=float32>

In [43]:
c.eval()

array([[ 3.,  3.,  3.,  3.],
       [ 3.,  3.,  3.,  3.]], dtype=float32)

#### tensor type

In [44]:
a=tf.ones((2,2),dtype=tf.int32)

In [45]:
a.eval()

array([[1, 1],
       [1, 1]])

In [46]:
b=tf.to_float(a)

In [47]:
b.eval()

array([[ 1.,  1.],
       [ 1.,  1.]], dtype=float32)

#### tensor shape manupulation

In [48]:
a = tf.ones(8)

In [49]:
a.eval()

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.], dtype=float32)

In [50]:
b=tf.reshape(a,(4,2))

In [51]:
b.eval()

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]], dtype=float32)

In [52]:
c=tf.reshape(a,(2,2,2)) #change the rank of the tensor

In [53]:
c.eval()

array([[[ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.]]], dtype=float32)

In [54]:
a=tf.ones(2)

In [55]:
a.get_shape()

TensorShape([Dimension(2)])

In [56]:
a.eval()

array([ 1.,  1.], dtype=float32)

In [57]:
b=tf.expand_dims(a,0)

In [58]:
b.eval()

array([[ 1.,  1.]], dtype=float32)

In [59]:
b.get_shape()

TensorShape([Dimension(1), Dimension(2)])

In [60]:
c=tf.expand_dims(a,1)

In [61]:
c.eval()

array([[ 1.],
       [ 1.]], dtype=float32)

In [62]:
c.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [63]:
d=tf.squeeze(b)

In [64]:
d.eval()

array([ 1.,  1.], dtype=float32)

In [65]:
d.get_shape()

TensorShape([Dimension(2)])

#### broadcasting

In [66]:
a= tf.ones((2,2))

In [67]:
a.eval()

array([[ 1.,  1.],
       [ 1.,  1.]], dtype=float32)

In [68]:
b=tf.range(0,2,1,dtype=tf.float32)

In [69]:
b.eval()

array([ 0.,  1.], dtype=float32)

In [70]:
c=a+b

In [71]:
c.eval()

array([[ 1.,  2.],
       [ 1.,  2.]], dtype=float32)

In [72]:
b=tf.range(0,2,1)

In [73]:
b.eval()

array([0, 1])

In [74]:
#c=a+b

* tf doesnt perform type casting under the hood

#### imperative and declarative programming
* consider a simple imperative programming
* imperative programming (we define how to get the answer)
* declarative progamming (we define what we want)

In [75]:
a=3
b=4
c=a+b
c

7

* tf equivalent of the above example

In [76]:
a=tf.constant(3)
b=tf.constant(4)
c=a+b

In [77]:
a

<tf.Tensor 'Const_1:0' shape=() dtype=int32>

In [78]:
c

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [79]:
c.eval()

7

In [80]:
tf.get_default_graph()

#### TF session

In [81]:
sess= tf.Session()

In [82]:
a=tf.ones((2,2))

In [83]:
b=tf.matmul(a,a)

In [84]:
b.eval(session=sess)

array([[ 2.,  2.],
       [ 2.,  2.]], dtype=float32)

* this above code evaluates b in the context of the sess instead of the hidden global session. 

In [85]:
sess.run(b) #another way 

array([[ 2.,  2.],
       [ 2.,  2.]], dtype=float32)

* infact b.eval(session=sess) is just syntactic sugar for calling sess.run(b)

#### tensoflow variables

* all the above computation we have used are constant tensors
* the style of programming so far has been funtionnal and not stateful
* much of Machine learning often depends on stateful computations 
* learning algorithiums are essentialy rules for updating stored tensor to explain the provided data
* if it is not possible to update the stored tensors, it would be hard to learn.
* tf.variable() class provides a wrapper around tensors that allow for stateful computations

In [86]:
a= tf.Variable(tf.ones((2,2)))

In [87]:
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32_ref>

In [88]:
#a.eval()

In [89]:
sess.run(a.assign(tf.zeros((3,3))))

ValueError: Dimension 0 in both shapes must be equal, but are 2 and 3 for 'Assign' (op: 'Assign') with input shapes: [2,2], [3,3].

* you should see that shape of the variable is fixed upon initialization and must be preserved with updates.
* tf.assign is itself a part of the underlying global tf.Graph instance 
* This allows tensorflow programs to update the internal state everytime they are run